// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcjpcsybvevfgeuisuoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjanBjc3lidmV2ZmdldWlzdW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTU2MTgsImV4cCI6MjA2OTkzMTYxOH0.N2Gtnm8AGvic65QKtLqZDKKuHSLN_tPBV9zoJ0J-8J4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});